import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import Test from '../components/Signin';
import { useSelector, useDispatch } from 'react-redux';
import RightDrawer from '../components/RightDrawer';
import { Box, Container } from '@mui/material';
import Layout from '../components/Layout';
import firebase, { tokenSignin, checkSignin } from '../actions/auth.action';
import { useEffect } from 'react';

export default function Auctions() {
  const auth = useSelector((state) => state.auth);
  const dispatch = useDispatch();
  
  useEffect(() => {
      dispatch(checkSignin());
  }, [])
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Layout>Auctions</Layout>
    
    </div>
  );
}
