import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';
import  {  checkSignin } from '../actions/auth.action';
import { useEffect, useState } from 'react';
import DashboardDrawer from '../components/DashboardDrawer';
import Reqsignin from '../components/Reqsignin';

export default function Mylistings() {
  const auth = useSelector((state) => state.auth);
  const dispatch = useDispatch();

  useEffect(() => {
      dispatch(checkSignin());
  }, [])

  return (
    !auth.authenticate?
    <Reqsignin/>:
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <DashboardDrawer/>
        <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '10vh',
      }}
    >
      <h2>My Listings</h2>
    </div>
    </div>
  );
}
