import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';
import firebase, { tokenSignin, checkSignin } from '../actions/auth.action';
import { useEffect } from 'react';
import DashboardDrawer from '../components/DashboardDrawer';
import Reqsignin from '../components/Reqsignin';
import Unauthorized from '../components/Unauthorized';
export default function Verifylistings() {
  const auth = useSelector((state) => state.auth);
  const dispatch = useDispatch();

  useEffect(() => {
      dispatch(checkSignin());
  }, [])


  return (  !auth.authenticate?
    <Reqsignin/>:
    auth.role=='admin'?
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardDrawer/>
        <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '10vh',
      }}
    >
      <h2>Verify Listings</h2>
    </div>

    </div>
    :
  <Unauthorized/>
  );
}
