export const authConstants = {
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_ERROR : "SIGNUP_ERROR",

    
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_ERROR: 'SIGNIN_ERROR',


    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_ERROR : "SIGNOUT_ERROR",
}

export const timelineConstants = {
    GET_TIMELINE_REQUEST: 'GET_TIMELINE_REQUEST',
    GET_TIMELINE_SUCCESS: 'GET_TIMELINE_SUCCESS',
    GET_TIMELINE_FAILURE:'GET_TIMELINE_FAILURE'
}

export const listConstants = {
    POST_LIST_REQUEST: 'POST_LIST_REQUEST',
    POST_LIST_SUCCESS: 'POST_LIST_SUCCESS',
    POST_LIST_FAILURE:'POST_LIST_FAILURE'
}